POST http://localhost:3000/movies
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBldGVyIiwiaWF0IjoxNjM1MjQ1NTAyfQ.isBItVzSXARk7H1zlEYbeS4Ha3c7ADD69rLMvW5nQKI

{
    "id": 6,
    "title": "Curso BackEnd",
    "poster": "https://i.imgur.com/abJNkWI.jpg",
    "synopsis": "The Godfather Part II presents two parallel storylines. One involves Mafia chief Michael Corleone in 1958/1959 after the events of the first movie; the othe...",
    "genres": [
      "Crime",
      "Drama"
    ],
    "year": 2021,
    "director": "Francis Ford Coppola"
}

###########

GET http://localhost:3000/movies/6
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBldGVyIiwiaWF0IjoxNjM1MjQ1NTAyfQ.isBItVzSXARk7H1zlEYbeS4Ha3c7ADD69rLMvW5nQKI

###########

GET http://localhost:3000/movies/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBldGVyIiwiaWF0IjoxNjM1MjQ1NTAyfQ.isBItVzSXARk7H1zlEYbeS4Ha3c7ADD69rLMvW5nQKI
############

PUT http://localhost:3000/movies/1
Content-Type: application/json


{
      "id": 1,
      "title": "Curso Back-End Web"
}

##########
DELETE http://localhost:3000/movies
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBldGVyIiwiaWF0IjoxNjM1MjQzMzM3fQ.mujD7TA_CXGas9LCoPjq8xqUo1jIw37AF0e-iPq5DNQ

{
      "id":1
}
