POST http://localhost:3000/movies
Content-Type: application/json

{
      "id": 11,
      "title": "Curso Back-End Web 2"
}

###########

GET http://localhost:3000/movies/

############

GET http://localhost:3000/movies/11

############


PUT http://localhost:3000/movies/1
Content-Type: application/json

{
      "id": 1,
      "title": "Curso Back-End Web"
}